export enum EducationLevel {
  ELEMENTARY = 'ELEMENTARY',
  MIDDLE_SCHOOL = 'MIDDLE_SCHOOL',
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  TECHNICAL = 'TECHNICAL',
  INCOMPLETE_HIGHER_EDUCATION = 'INCOMPLETE_HIGHER_EDUCATION',
  HIGHER_EDUCATION = 'HIGHER_EDUCATION',
  POSTGRADUATE = 'POSTGRADUATE'
}
