export const ROUTES_KEYS = {
  classroomId: 'classroomId',
  classrooms: 'turmas',
  edit: 'editar',
  finance: 'financeiro',
  forgotPassword: 'esqueci-minha-senha',
  help: 'ajuda-e-suporte',
  home: 'inicio',
  itemId: 'itemId',
  lessonAttendance: 'chamada',
  lessonId: 'lessonId',
  lessons: 'aulas',
  login: 'login',
  management: 'cadastro',
  notFound: 'recurso-nao-encontrado',
  people: 'pessoas',
  personId: 'personId',
  register: 'registrar',
  settings: {
    accountInformation: 'dados-da-conta',
    activityLog: 'registro-de-atividades',
    adminAccess: 'acesso-administrativo',
    attendanceScores: 'chamadas-e-pontuacoes',
    departments: 'departamentos',
    headquartersManagement: 'gerenciamento-da-sede',
    inactiveRecords: 'cadastros-inativos',
    index: 'configuracoes',
    itemsManagement: 'cadastro-de-items',
    schoolInformation: 'dados-da-escola',
    teacherAccess: 'acesso-professor',
  },
  signUp: 'usuarios/cadastrar',
}
